version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: rest_vip
      EXPRESS_PORT: 3000
    links:
      - db
    ports:
      - 3000:3000

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rest_vip

